if (SERVER) then
	AddCSLuaFile()
end
CreateConVar("kevlar_debug","0",FCVAR_REPLICATED+FCVAR_ARCHIVE )
CreateConVar("kevlar_enabled","0",FCVAR_REPLICATED+FCVAR_ARCHIVE )
KSWEP_ARMOR_I=5
KSWEP_ARMOR_IIA=10
KSWEP_ARMOR_II=15
KSWEP_ARMOR_IIIA=20
KSWEP_ARMOR_CRISAT=25
KSWEP_ARMOR_III=30
KSWEP_ARMOR_IV=40
