if (SERVER) then
	AddCSLuaFile()
end


sound.Add({
	name="weapon_kswep.single",
	volume=1.0,
	pitch={155,165},
	sound="^weapons/sg550/sg550-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_law.single",
	volume=1.0,
	pitch={55,60},
	sound="^weapons/357_fire2.wav",
	level=165,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_m4.single",
	volume=1.0,
	pitch={155,165},
	sound="^weapons/m4a1/m4a1_unsil-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_akm.single",
	volume=1.0,
	pitch={175,185},
	sound="^weapons/ak47/ak47-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_ak74.single",
	volume=1.0,
	pitch={200,205},
	sound="^weapons/ak47/ak47-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_glock19.single",
	volume=1.0,
	pitch={185,195},
	sound="^weapons/glock/glock18-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_fiveseven.single",
	volume=1.0,
	pitch={125,135},
	sound="^weapons/fiveseven/fiveseven-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_nagant.single",
	volume=1.0,
	pitch={145,155},
	sound="^weapons/pistol/pistol_fire3.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_p228.single",
	volume=1.0,
	pitch={185,195},
	sound="^weapons/elite/elite-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_judge.single",
	volume=0.7,
	pitch={225,245},
	sound="^weapons/deagle/deagle-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_mac11.single",
	volume=1,
	pitch={225,235},
	sound="^weapons/usp/usp_unsil-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_p90.single",
	volume=1,
	pitch={245,255},
	sound="^weapons/p90/p90-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_p238.single",
	volume=1.0,
	pitch={185,195},
	sound="^weapons/g3sg1/g3sg1-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_mp5.single",
	volume=1.0,
	pitch={185,195},
	sound="^weapons/mp5navy/mp5-1.wav",
	level=140,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_mp510.single",
	volume=1.0,
	pitch={175,185},
	sound="^weapons/mp5navy/mp5-1.wav",
	level=140,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswep_test.single762",
	volume=1.0,
	pitch={125,135},
	sound="^weapons/g3sg1/g3sg1-1.wav",
	level=145,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_awm.single",
	volume=1.0,
	pitch={195,205},
	sound="^weapons/awp/awp1.wav",
	level=155,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_shotgun.single",
	volume=1.0,
	pitch={120,120},
	sound="^weapons/shotgun/shotgun_fire6.wav",
	level=155,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_ghostgun.single",
	volume=1.0,
	pitch={70,75},
	sound="^weapons/awp/awp1.wav",
	level=160,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_j22.single",
	volume=1,
	pitch={245,255},
	sound="^weapons/sg552/sg552-1.wav",
	level=135,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswep.singlesilenced",
	volume=1,
	pitch={245,255},
	sound="^weapons/sg550/sg550-1.wav",
	level=120,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_scout.single",
	volume=1.0,
	pitch={75,80},
	sound="^weapons/scout/scout_fire-1.wav",
	level=155,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_scout_556.single",
	volume=1.0,
	pitch={95,105},
	sound="^weapons/scout/scout_fire-1.wav",
	level=155,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_scar17.single",
	volume=1.0,
	pitch={125,135},
	sound="^weapons/g3sg1/g3sg1-1.wav",
	level=160,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_usp45.single",
	volume=1.0,
	pitch={165,170},
	sound="^weapons/usp/usp_unsil-1.wav",
	level=140,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_usp45.single_sup",
	volume=0.7,
	pitch={205,210},
	sound="^weapons/usp/usp_unsil-1.wav",
	level=110,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_m4.single_sup",
	volume=1.0,
	pitch={195,205},
	sound="^weapons/m4a1/m4a1_unsil-1.wav",
	level=110,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kswept_300blk.single_sup",
	volume=0.6,
	pitch={185,190},
	sound="^weapons/m4a1/m4a1_unsil-1.wav",
	level=110,
	channel=CHAN_WEAPON
})
sound.Add({
	name="weapon_kgrent_flashbang.detonate",
	volume=1,
	pitch={195,205},
	sound="^weapons/aug/aug-1.wav",
	level=145,
	channel=CHAN_WEAPON
})	
