if (SERVER) then
	AddCSLuaFile()
end


sound.Add({
	name="weapon_kswep.single",
	volume=1.0,
	pitch={155,165},
	sound="weapons/sg550/sg550-1.wav",
	level=145,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_m4.single",
	volume=1.0,
	pitch={155,165},
	sound="weapons/m4a1/m4a1_unsil-1.wav",
	level=145,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_glock19.single",
	volume=1.0,
	pitch={185,195},
	sound="weapons/glock/glock18-1.wav",
	level=145,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_mp5.single",
	volume=1.0,
	pitch={185,195},
	sound="weapons/mp5navy/mp5-1.wav",
	level=140,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_mp510.single",
	volume=1.0,
	pitch={175,185},
	sound="weapons/mp5navy/mp5-1.wav",
	level=140,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswep_test.single762",
	volume=1.0,
	pitch={125,135},
	sound="weapons/g3sg1/g3sg1-1.wav",
	level=145,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_awm.single",
	volume=1.0,
	pitch={195,205},
	sound="weapons/awp/awp1.wav",
	level=155,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswep.singlesilenced",
	volume=1,
	pitch={245,255},
	sound="weapons/sg550/sg550-1.wav",
	level=120,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_scout.single",
	volume=1.0,
	pitch={75,80},
	sound="weapons/scout/scout_fire-1.wav",
	level=155,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_scout_556.single",
	volume=1.0,
	pitch={95,105},
	sound="weapons/scout/scout_fire-1.wav",
	level=155,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_usp45.single",
	volume=1.0,
	pitch={165,170},
	sound="weapons/usp/usp_unsil-1.wav",
	level=140,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_usp45.single_sup",
	volume=0.7,
	pitch={205,210},
	sound="weapons/usp/usp_unsil-1.wav",
	level=110,
	channel=CHAN_STATIC
})
sound.Add({
	name="weapon_kswept_m4.single_sup",
	volume=1.0,
	pitch={195,205},
	sound="weapons/m4a1/m4a1_unsil-1.wav",
	level=110,
	channel=CHAN_STATIC
})
	
